models:
  mask_rcnn_weights : weights\MaskRCNN_2class
  yolov3_weights : weights\yolov3.weights
  yolov3_cfg : config\yolov3.cfg
  yolov3_class : config\coco.names

email:
  sender_email_address: # SENDER EMAIL HERE
  email_password : # PUBLIC EMAIL PASSWORD HERE
  receiver_email_address : # RECIEVER PASSWORD HERE
  intruder_image_folder : Intruders